export default [
    {order: 'Pre Pick and Pack', index: 0, minsPerUnit: 6},
    {order: 'Bag and tag', index: 1, minsPerUnit: 2.5},
    {order: 'Arranging a courier collection and delivery', index: 2, minsPerUnit: "n/a"},
    {order: 'Sewing', index: 3, minsPerUnit: 22.5},
    {order: 'Swing Tags', index: 4, minsPerUnit: 2.21},
    {order: 'Order Personalisation', index: 5, minsPerUnit: 12.27},
    {order: 'Barcoding/ Labelling', index: 6, minsPerUnit: 0.10},
    {order: 'Manual Shipment', index: 7, minsPerUnit: 0.15},
    {order: 'Making up a Gift Pack', index: 8, minsPerUnit: 2.05},
    {order: 'Manual Booking In', index: 9, minsPerUnit: 0.75},
    // {order: 'Quality Check (Visual)', index: 10}, minsPerUnit: ,
    {order: 'Quality Check: Ceramics', index: 11, minsPerUnit: 2.5},
    {order: 'Quality Check: Garments', index: 12, minsPerUnit: 3},
    {order: 'Steam, Fold and Repack', index: 13, minsPerUnit: 10},
    {order: 'Rebagging', index: 14, minsPerUnit: 5.69},
    {order: 'Barcoding of Fabric Rolls', index: 15, minsPerUnit: 10},
    {order: 'Shipping of Fabric Rolls', index: 16, minsPerUnit: 5},
    {order: 'Bespoke QC', index: 17, minsPerUnit: ["Flat Cost", 10]},
    {order: 'Stock Count', index: 18, minsPerUnit: "n/a"},
    {order: 'Quality Check: Accessories', index: 19, minsPerUnit: 2.5},
]